### ISSUE TITLE
Cric and zoom

### ISSUE THREAD

**Issue by Bahnzo** [jairoxyz/kodistuff#1]
I'm still getting errors after the update. Something on my side?

**Comment by jairoxyz** [comment]
I know. I added another fix to zoom. Try again.

**Comment by Bahnzo** [comment]
This was with the latest zip pushed.

**Comment by jairoxyz** [comment]
They change code so often ....

**Comment by Bahnzo** [comment]
Yes they do. Thanks for the update.
