### ISSUE TITLE
Still having troubles....

### ISSUE THREAD

**Issue by Bahnzo** [jairoxyz/kodistuff#2]
I've had problems with zoom. Not the "super encryted" one we talked about, but the regular zoom that always worked. I'll post the log. 

Also, I still can't get saw working, even with the latest. Dunno if they are changing that fast or it's me. I've always been using wiz1 and it's been super stable until the last couple weeks. 

zoom log:
`14:57:11.746 T:10864  NOTICE: VideoPlayer: Opening:  playpath= swfurl=http://static.zoomtv.me/player/7.10/jwplayer.flash.swf flashver=WIN/25,0,0,119 conn=S: conn=S: conn=S: conn=S:V&gt;JWhui^@2ESdu0?}&gt;AN live=1 token=Q!lrB@G1)ww(-dQ4J4 pageUrl=http://www.zoomtv.me/embed.php?v=MLB2h
14:57:11.746 T:10864 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:57:11.746 T:10864   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
14:57:11.746 T:10920  NOTICE: Creating InputStream
14:57:11.747 T:10920 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol( playpath= swfurl=http) in  playpath= swfurl=http://static.zoomtv.me/player/7.10/jwplayer.flash.swf flashver=WIN/25,0,0,119 conn=S: conn=S: conn=S: conn=S:V&gt;JWhui^@2ESdu0?}&gt;AN live=1 token=Q!lrB@G1)ww(-dQ4J4 pageUrl=http://www.zoomtv.me/embed.php?v=MLB2h
14:57:11.747 T:10920   ERROR: CVideoPlayer::OpenInputStream - error opening [ playpath= swfurl=http://static.zoomtv.me/player/7.10/jwplayer.flash.swf flashver=WIN/25,0,0,119 conn=S: conn=S: conn=S: conn=S:V&gt;JWhui^@2ESdu0?}&gt;AN live=1 token=Q!lrB@G1)ww(-dQ4J4 pageUrl=http://www.zoomtv.me/embed.php?v=MLB2h]
14:57:11.747 T:10920  NOTICE: CVideoPlayer::OnExit()`

saw log:
`14:55:36.809 T:10864  NOTICE: VideoPlayer: Opening: rtmp://flash playpath= swfVfy=1 flashver=WIN/2024,0,0,221 timeout=25 swfUrl= live=true pageUrl=http://www3.sawlive.tv/embed/watch/ZlNmE5M2FkODU1MzBlMGJhZjgzZDEwZjc6NGQ1NDUxMzU0ZDU0NDUzNDRlNDQ2MzMyNGQ3NzNkM2Q_/bGFnenpwYTM6MWRhNDc4ZjEwMTJiMWZmZDk5OWExYmM0NjBkZTAzMTE6ZDRjY2VkYj
14:55:36.809 T:10864 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:55:36.809 T:10864   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
14:55:36.810 T:6816  NOTICE: Creating InputStream
14:55:36.811 T:6816   ERROR: CVideoPlayer::OpenInputStream - error opening [rtmp://flash playpath= swfVfy=1 flashver=WIN/2024,0,0,221 timeout=25 swfUrl= live=true pageUrl=http://www3.sawlive.tv/embed/watch/ZlNmE5M2FkODU1MzBlMGJhZjgzZDEwZjc6NGQ1NDUxMzU0ZDU0NDUzNDRlNDQ2MzMyNGQ3NzNkM2Q_/bGFnenpwYTM6MWRhNDc4ZjEwMTJiMWZmZDk5OWExYmM0NjBkZTAzMTE6ZDRjY2VkYj]
14:55:36.811 T:6816  NOTICE: CVideoPlayer::OnExit()`

**Comment by jairoxyz** [comment]
I made some changes to saw catcher but can only test with 2 or 3 24/7 channels. I'll have a look at zoom too.

**Comment by Bahnzo** [comment]
Would it help to have my LSP code for Wiz1 for testing? They are saw and usually have events around the clock.

**Comment by jairoxyz** [comment]
Sure. I also use wiz1 via LSP for testing.

**Comment by jairoxyz** [comment]
I think I fixed zoom rtmp. Please give it a try.

**Comment by Bahnzo** [comment]
Yep, the zoom rtmp looks good, thanks so much. 

However, it looks like zoom is maybe using another/new method. This MLB network link uses it, it used to be the zoom2 you had found a way to grab the link from. http://www.vipboxtv.me/baseball/294437/2/mlb-network-stream.html 

It's got a new .js: http://zome.zoomtv.me/js/embedhd.min.js     

That's all I found with a quick look. SD just gives a "Web request failed" so I knew something was up there. 

I'll send you link for my Wiz1 script over on TVaddons...

**Comment by jairoxyz** [comment]
Yes, also have a new js for the rtmp streams. Fixed that one too. HLS should be working again.

**Comment by Bahnzo** [comment]
Groovy

**Comment by Bahnzo** [comment]
Well, hate to say it,  but neither of the zoom works. I can provide a log if you need it.

**Comment by jairoxyz** [comment]
Not necessary. I know what's wrong. They read the forum or this GIT and change code whenever we update. I'll think of something.

**Comment by jairoxyz** [comment]
Give it another try. RTMP seems to be working. HLS should also do but won't work for me. No idea why.

**Comment by Bahnzo** [comment]
Yeah, they got it already. They (VIP) need to do something along the lines of what Openload does for tv/movie streaming. Would save a lot of trouble and continue to get them ad revenue.

**Comment by jairoxyz** [comment]
They take themselves way too important. I don't even watch their streams because too slow at my location. Anyway, fixed rtmp for now.

**Comment by Bahnzo** [comment]
Well, I appreciate you continuing to irritate them :)

**Comment by jairoxyz** [comment]
They really have a sense of humor:   iscche = 'iscache = "middlefinger"'

-lol-

**Comment by jairoxyz** [comment]
Delete vipbox/zoom from public repos ;)
