### ISSUE TITLE
Is everything going to be on that site that starts with "me"?

### ISSUE THREAD

**Issue by heio123** [jairoxyz/kodistuff#6]

**Comment by gdx2015** [comment]
Hello Jairox! Where  you meet now ;)

goldonx

**Comment by 1nvisable** [comment]
All the best Jairox !!
Thanks for your work over the last year or so

**Comment by jairoxyz** [comment]
Yes, I will put my SD updates there for the moment.

@goldonx: you still have my mail? please mail me or post your mail here.

**Comment by Bahnzo** [comment]
Anyone wanna pm me what site this is?

**Comment by jairoxyz** [comment]
Hey Bahnzo. No idea how to PM you. SD will be here for now: https://mega.nz/#F!sqZ3gTpK!_2bkq3aXjWfRPGcKr7mRlg . I'll delete this post when you have copied the url. Please confirm. Got any mail where to reach you?

**Comment by Bahnzo** [comment]
got it....bahnzo2020@gmail.com is my anon email.

**Comment by 1nvisable** [comment]
I haven't had time to create an alias email. I don't know about you but this Smash fella keeps putting SD in his repository.
According to twitter he has an updated version, is this your version Jairox ?

I'm not a fan of this dude by the way I'm happy to ask him to remove it from his repository.

Sent from my HTC

----- Reply message -----

**Comment by 1nvisable** [comment]
I created an email...
1nvisable@gmx.co.uk

**Comment by heio123** [comment]
Hey is there a easy way to contact you?

**Comment by newness2t** [comment]
Can you please fix zunox and streams from rojadirecta like max and others

**Comment by jairoxyz** [comment]
SD update is available.

**Comment by heio123** [comment]
fix for saw available? thanks very much

**Comment by jairoxyz** [comment]
yep

**Comment by heio123** [comment]
Think zunox changed again

**Comment by devilsport** [comment]
ok will review SD this week to have it fit for the new season. Maybe people can meet again at tvaddons.co.

**Comment by devilsport** [comment]
SD update available

**Comment by kabcasa** [comment]
hi jairox   we miss 
there is a way to get last update .tks

**Comment by devilsport** [comment]
hey @kabcasa - post an email address here where to reach u

**Comment by devilsport** [comment]
new SD update available

**Comment by kabcasa** [comment]
Kabcasa@gmail.com
Tks
